expenses/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^expenses/$', "expenses.views.index" ,  name="expenses" ),
    url(r'^expenses/search$', "expenses.views.search" ,  name="search_expenses" ),
    url(r'^expenses/new/$', "expenses.views.new" ,  name="new_expense" ),
    url(r'^expenses/(?P<id>\d+)/edit/$', "expenses.views.edit" ,  name="edit_expense" ),
    url(r'^expenses/(?P<id>\d+)/delete/$', "expenses.views.delete" ,  name="delete_expense" ),
]

foraccount/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("main.urls")),
    url(r'^', include("expenses.urls")),
    url(r'^', include("expense_types.urls")),
    url(r'^', include("profits.urls")),
]

main/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', "main.views.index" ,  name="home" ),
]

expenses/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from expense_types.models import ExpenseType
from main.utils import UserUtil
from datetime import date

# Create your models here.


class Expense(models.Model):
    year         = models.IntegerField( blank = False )
    month        = models.IntegerField( blank = False )
    date_expense = models.DateField( blank = False )
    value        = models.DecimalField(max_digits = 20, decimal_places = 2, blank = False )
    description  = models.TextField( blank = True, null=True, max_length = 200 )
    type         = models.ForeignKey( ExpenseType 
        , blank = False
        , related_name="expense"
        , limit_choices_to={
            'user' : UserUtil.get_current_user(),
            'father_expense_type' : None
        })
    subtype      = models.ForeignKey( ExpenseType
        , blank = True
        , null = True
        , related_name="expense_subtypes")
    user         = models.ForeignKey(User)
    
    @staticmethod
    def total_for(user, month=date.today().month  , year=date.today().year  ):
        return Expense.objects.filter(user=user,year=year,month=month).aggregate(Sum("value"))
       

home/ubuntu/workspace/expenses/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from expense_types.models import ExpenseType
from main.utils import UserUtil
from datetime import date

# Create your models here.


class Expense(models.Model):
    year         = models.IntegerField( blank = False )
    month        = models.IntegerField( blank = False )
    date_expense = models.DateField( blank = False )
    value        = models.DecimalField(max_digits = 20, decimal_places = 2, blank = False )
    type         = models.ForeignKey( ExpenseType 
        , blank = False
        , limit_choices_to={
            'user' : UserUtil.get_current_user()
        })
    user         = models.ForeignKey(User)
    
    @staticmethod
    def total_for(user, month=date.today().month  , year=date.today().year  ):
        return Expense.objects.filter(user=user,year=year,month=month).aggregate(Sum("value"))
       

expenses/forms.py
# -*- codding: UTF-8 -*-
from django import forms
from datetime import date
from main.utils import DateUtil
from models import Expense
from expense_types.models import ExpenseType
from main.utils import UserUtil


class SearchExpensesForm(forms.Form):
    
    year = forms.ChoiceField(required=True , 
        widget=forms.Select(attrs={"class":"form-control"}),
        choices =  ((str(x), x) for x in DateUtil.YEARS ) , initial = date.today().year )
    month = forms.ChoiceField(required=True ,
        widget=forms.Select(attrs={"class":"form-control"}),
        choices = ((str(x), x) for x in DateUtil.MONTHS ) , initial = date.today().month )
    
    def is_valid(self):
        valid = True
        if not super(SearchExpensesForm , self).is_valid():
            valid = False
        return valid

class ExpenseForm(forms.ModelForm):
    
    class Meta:
        model = Expense
        fields = [ 'type' , 'subtype' , 'value' , 'date_expense' , 'description'  ]
        widgets = {
            'year': forms.Select(choices = ((str(x), x) for x in DateUtil.YEARS ), attrs={'class': 'form-control'}),
            'month': forms.Select(choices = ((str(x), x) for x in DateUtil.MONTHS ) , attrs={'class': 'form-control'} ),
            'date_expense' : forms.DateInput(attrs={"class" :"form-control" } ),
            'value' : forms.NumberInput(attrs={"class" :"form-control" , "s" :"lol"} ),
        }
    
    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        self.fields['subtype'].queryset = ExpenseType.objects.none()        
    

expenses/views.py
# -*- codding: UTF-8 -*-
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from datetime import date
from models import Expense
from expense_types.models import ExpenseType
from forms import SearchExpensesForm
from forms import ExpenseForm
from main.utils import UserUtil
# Create your views here.


def index(request):
    form = SearchExpensesForm()
    user = UserUtil.get_current_user()
    expenses = Expense.objects.filter(user=user , year = date.today().year , month = date.today().month )
    return render(request ,"expenses/index.html" , { "expenses": expenses, "form" : form  }) 

def search(request):
    form = SearchExpensesForm(request.GET )
    user = UserUtil.get_current_user()
    expenses = []
    if( form.is_valid ):
        expenses = Expense.objects.filter(user=user, year = form.data['year'] , month = form.data['month'])
    return render(request ,"expenses/index.html" , { "expenses": expenses , "form" : form }) 

def new(request):
    form = ExpenseForm(request.POST or None , initial = { 'year' : date.today().year , 'month' : date.today().month })
    
    type_id = 0
    if( request.POST ):
        type_id = int( request.POST.get('type') or 0 )
    form.fields['subtype'].queryset = ExpenseType.objects.filter( father_expense_type = type_id )
    if(form.is_valid()):
        expense = form.save(commit=False)
        expense.user = UserUtil.get_current_user()
        expense.year = expense.date_expense.year
        expense.month = expense.date_expense.month
        expense.save()
        return HttpResponseRedirect( "{}?month={}&year={}".format( reverse("search_expenses"),  expense.month , expense.year ) )
    return render(request ,"expenses/form.html" , { "form" : form } ) 
    
def edit(request , id):    
    user = UserUtil.get_current_user()
    obj = Expense.objects.get(pk=id, user = user )
    form = ExpenseForm(request.POST or None, instance = obj )
    
    type_id = obj.type.pk  
    if( request.POST ):
        type_id = int( request.POST.get('type') or 0 )
    
    form.fields['subtype'].queryset = ExpenseType.objects.filter( father_expense_type = type_id )
    if form.is_valid():
        expense = form.save(commit=False)
        expense.year = expense.date_expense.year
        expense.month = expense.date_expense.month
        form.save()
        return HttpResponseRedirect( "{}?month={}&year={}".format( reverse("search_expenses"),  expense.month , expense.year ) )
    return render(request ,"expenses/form.html" , { "form" : form } ) 
    
def delete(request , id):  
    if(request.POST):
        expense = Expense.objects.get(pk=id , user = UserUtil.get_current_user())
        expense.delete()
        return HttpResponseRedirect( "{}?month={}&year={}".format( reverse("search_expenses"),  expense.month , expense.year ) )
    else:
        form = ExpenseForm(instance = Expense.objects.get(pk=id , user = UserUtil.get_current_user()))
    return render(request ,"expenses/delete.html" , { "form" : form  } ) 

expenses/templates/expenses/delete.html
{% extends "main-template.html" %}
	
{% block body %}
    <h1 class="page-header">Expense</h1>
   
    <form role="form" action="{{action}}" method="post">
        {% include "main/snippets/_form_snippet.html" with back_url="expenses" readonly="disabled:disabled"  %}
        <div class="row">
          <div class="col-sm-12">
            <button type="submit" class="btn btn-danger"><span class="fa fa-trash" style="margin-right:5px"></span>Delete</button>
            <a href="{% url 'expenses' %}" class="btn btn-warning"><span class="fa fa-reply" style="margin-right:5px"></span> Cancel</a>
          </div>
        </div
    </form>
{% endblock %}

expenses/templates/expenses/form.html
{% extends "main-template.html" %}
	
{% block body %}
    <h1 class="page-header">Expense</h1>
    
    <form role="form" action="{{action}}" method="post">
        {% include "main/snippets/_form_snippet.html"  %}
        {% include "main/snippets/_form_actions_snippet.html" with back_url="expenses"  %}
    </form>
    
    <script>
      var k = null;
      window.onload=function(){
        document.getElementById("id_value").focus();
        $("#id_type").change( function(evt){
          var id = parseInt($(this).val());
          if(id){
            var input = $("#id_subtype").clone().empty();
            $(input).append($('<option>', {value: "" , text: "---------" }))
            $.get("/expense_types/"+id+"/subtypes/" , function(subtypes){
              for(var i = 0 ; i < subtypes.length ; i++ ){
                var sub = subtypes[i];
                $(input).append($('<option>', {value: sub.pk , text: sub.name }))
              }
              $("#id_subtype").replaceWith(input);
            });
            
          }
        });
      }
    </script>
{% endblock %}

expenses/templates/expenses/index.html
{% extends "main-template.html" %}
	    
	
{% block body %}
    <h1 class="page-header">Expenses <a class="btn btn-success btn-sm pull-right" href="./new">Add</a></h1>
    
    <form action="./search">
        <div class="row">
            
            {% for field in form %}
              <div class="col-xs-3">
                {{ field.label_tag }}
                {% if field.errors %} 
                    {{ field.errors.0 }}
                {% endif %}
                {{ field }}
              </div>
            {% endfor %}
             
        </div>
        <br/>
        <div class="row">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Search">
            </div>
        </div>
    </form>
    
    <div class="row">
        <div class="col-xs-12">
            <table class="table table-striped table-condensed">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nature</th>
                        <th>Date</th>
                        <th>Value</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in expenses %}
                        <tr>
                            <td>{{item.id}}</td>
                            <td>{{item.type.name }}
                                {% if item.type.description %}
                                <span class="fa fa-question-circle" title="{{item.type.description}}"></span>
                                {% endif %}
                            </td>
                            <td>{{item.date_expense | date:"d/m/Y" }}</td>
                            <td>{{item.value | floatformat:"2"}}</td>
                            <td>
                                {% include "main/snippets/_actions_snippet.html" %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>                
        </div>
    </div>
    
    
    
{% endblock %}
	